from pymongo import MongoClient
import os
from dotenv import load_dotenv

load_dotenv()
client = MongoClient(os.getenv("MONGO_URI"))
db = client["phishing_db"]
col = db["taxonomy_preset"]

col.drop()  # clear before re-seeding

PRESET = [
  {"id":"phi-001","type":"Email Phishing","subtype":"Generic Mass Campaign","channel":"Email","era":"1995–2005","sophistication":"Low","technique":"Bulk emails impersonating AOL or banks with generic lure messages asking users to verify credentials","indicators":["misspelled domain","urgent language","generic greeting like Dear Customer"],"target_sector":"General Public","success_rate":"High (pre-awareness era)","source":"Preset DB"},
  {"id":"phi-002","type":"Spear Phishing","subtype":"Targeted Individual","channel":"Email","era":"2005–present","sophistication":"High","technique":"Personalised emails using victim name, role, and organisation details gathered via LinkedIn and OSINT","indicators":["personal references","spoofed sender","legitimate-looking domain"],"target_sector":"Corporate, Government","success_rate":"High","source":"Preset DB"},
  {"id":"phi-003","type":"Whaling","subtype":"CEO / Executive Targeting","channel":"Email","era":"2008–present","sophistication":"Very High","technique":"Highly crafted emails impersonating board members or legal counsel targeting CFOs to authorise wire transfers","indicators":["executive name spoofed","urgent wire transfer","no attachment — pure social engineering"],"target_sector":"Finance, C-Suite","success_rate":"High","source":"Preset DB"},
  {"id":"phi-004","type":"Smishing","subtype":"SMS Credential Theft","channel":"SMS","era":"2010–present","sophistication":"Medium","technique":"Text messages impersonating banks, parcel services, or HMRC with short URLs leading to credential harvesting pages","indicators":["short URL","impersonates known brand","asks for OTP or card number"],"target_sector":"General Public, Banking","success_rate":"Medium-High","source":"Preset DB"},
  {"id":"phi-005","type":"Vishing","subtype":"Phone Call Fraud","channel":"Voice","era":"2006–present","sophistication":"Medium","technique":"Caller impersonates bank fraud team or HMRC demanding immediate action or personal information","indicators":["caller ID spoofed","urgency and threats","asks for card PIN or OTP verbally"],"target_sector":"Elderly, General Public","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-006","type":"Clone Phishing","subtype":"Duplicated Legitimate Email","channel":"Email","era":"2010–present","sophistication":"High","technique":"Attacker copies a real previously delivered email, replaces attachment or link with malicious version, re-sends from spoofed address","indicators":["near-identical to legitimate email","re-sent notification","replaced link or attachment"],"target_sector":"Corporate","success_rate":"High","source":"Preset DB"},
  {"id":"phi-007","type":"Pharming","subtype":"DNS Poisoning Redirect","channel":"Web","era":"2004–2012","sophistication":"Very High","technique":"Corrupts DNS cache to redirect users from legitimate URLs to fake sites without any user action required","indicators":["HTTPS missing","slight URL mismatch","certificate warning"],"target_sector":"Banking, E-commerce","success_rate":"High","source":"Preset DB"},
  {"id":"phi-008","type":"Social Media Phishing","subtype":"Fake Profile Lure","channel":"Social Media","era":"2010–present","sophistication":"Medium","technique":"Creates fake social media profiles mimicking colleagues, recruiters, or celebrities to extract credentials or deploy malware","indicators":["newly created profile","unsolicited DM","link to external login page"],"target_sector":"General Public, Corporate","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-009","type":"Business Email Compromise","subtype":"Supplier Invoice Fraud","channel":"Email","era":"2013–present","sophistication":"Very High","technique":"Compromises or spoofs a trusted supplier email to redirect invoice payments to attacker-controlled accounts","indicators":["changed bank details","urgency","reply-to address differs from from address"],"target_sector":"Finance, Procurement","success_rate":"Very High","source":"Preset DB"},
  {"id":"phi-010","type":"Credential Harvesting","subtype":"Fake Login Page","channel":"Web","era":"2003–present","sophistication":"Medium","technique":"Creates pixel-perfect copy of Microsoft 365, Google, or banking login page hosted on lookalike domain","indicators":["lookalike domain","HTTPS present (false trust)","immediate redirect after login"],"target_sector":"Corporate, General Public","success_rate":"High","source":"Preset DB"},
  {"id":"phi-011","type":"Email Phishing","subtype":"COVID-19 Lure","channel":"Email","era":"2020–2022","sophistication":"Medium","technique":"Exploited pandemic fear using WHO, NHS, or government impersonation to distribute malware or steal credentials","indicators":["health emergency language","government logo","malicious attachment disguised as health guidance"],"target_sector":"General Public","success_rate":"High (fear-driven)","source":"Preset DB"},
  {"id":"phi-012","type":"Spear Phishing","subtype":"HR / Payroll Redirect","channel":"Email","era":"2015–present","sophistication":"High","technique":"Impersonates HR department asking employee to update bank details for payroll on a fake internal portal","indicators":["internal HR tone","fake intranet URL","time pressure around pay dates"],"target_sector":"Corporate Employees","success_rate":"High","source":"Preset DB"},
  {"id":"phi-013","type":"Smishing","subtype":"Parcel Delivery Scam","channel":"SMS","era":"2019–present","sophistication":"Low-Medium","technique":"Fake Royal Mail, DHL, or FedEx SMS claiming package held due to unpaid fee — links to fake payment page","indicators":["delivery brand impersonation","small fee requested","bit.ly or tiny URL"],"target_sector":"General Public","success_rate":"High","source":"Preset DB"},
  {"id":"phi-014","type":"Social Media Phishing","subtype":"Giveaway / Prize Scam","channel":"Social Media","era":"2012–present","sophistication":"Low","technique":"Fake giveaway posts impersonating celebrities or brands requiring users to click link and provide personal details","indicators":["too-good prize","celebrity account lookalike","link to external form"],"target_sector":"General Public","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-015","type":"Business Email Compromise","subtype":"CEO Fraud / Wire Transfer","channel":"Email","era":"2014–present","sophistication":"Very High","technique":"Attacker impersonates CEO emailing CFO directly requesting urgent confidential wire transfer, bypassing normal approval process","indicators":["CEO name in from field","no email thread history","request to keep confidential"],"target_sector":"Finance Departments","success_rate":"Very High","source":"Preset DB"},
  {"id":"phi-016","type":"Credential Harvesting","subtype":"Microsoft 365 Phishing","channel":"Email + Web","era":"2017–present","sophistication":"High","technique":"Email with SharePoint or Teams notification lure leads to cloned Microsoft login page with real-time credential relay to attacker","indicators":["Microsoft branding","real-time MFA bypass","oauth token theft"],"target_sector":"Corporate","success_rate":"High","source":"Preset DB"},
  {"id":"phi-017","type":"Vishing","subtype":"Tech Support Scam","channel":"Voice + Web","era":"2008–present","sophistication":"Low-Medium","technique":"Pop-up warning claims device is infected; victim calls displayed number and is convinced to give remote access","indicators":["browser pop-up lock","Microsoft/Apple branding","call centre with accent"],"target_sector":"Non-technical users, Elderly","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-018","type":"Spear Phishing","subtype":"Lateral Movement via Compromised Contact","channel":"Email","era":"2016–present","sophistication":"Very High","technique":"Once one employee account is compromised, attacker emails their contacts from the real account with malicious links — high trust","indicators":["sent from known contact","unexpected attachment","unusual request in familiar tone"],"target_sector":"Corporate Networks","success_rate":"Very High","source":"Preset DB"},
  {"id":"phi-019","type":"Email Phishing","subtype":"Tax Refund / HMRC Scam","channel":"Email","era":"2007–present","sophistication":"Low-Medium","technique":"Impersonates HMRC or IRS offering tax refund, directing victim to credential harvesting page to submit banking details","indicators":["government logo and tone","refund offer","asks for banking details"],"target_sector":"General Public","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-020","type":"Pharming","subtype":"Home Router DNS Attack","channel":"Web","era":"2015–2020","sophistication":"High","technique":"Malware changes home router DNS settings, silently redirecting all banking traffic to attacker-controlled cloned sites","indicators":["certificate mismatch","router firmware vulnerability","invisible to victim"],"target_sector":"Home Banking Users","success_rate":"High","source":"Preset DB"},
  {"id":"phi-021","type":"Clone Phishing","subtype":"DocuSign / E-signature Lure","channel":"Email","era":"2018–present","sophistication":"High","technique":"Spoofs DocuSign notification emails with real branding; link leads to credential harvesting page designed to steal Microsoft or Google credentials","indicators":["DocuSign branding","urgency to sign","external URL not docusign.com"],"target_sector":"Corporate, Legal, Finance","success_rate":"High","source":"Preset DB"},
  {"id":"phi-022","type":"Social Media Phishing","subtype":"LinkedIn Job Offer Scam","channel":"Social Media","era":"2016–present","sophistication":"Medium-High","technique":"Fake recruiter contacts target with tailored job offer on LinkedIn, eventually asking them to open a document containing malware","indicators":["flattering job offer","PDF or ZIP attachment","newly created recruiter profile"],"target_sector":"Job Seekers, Tech Professionals","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-023","type":"Smishing","subtype":"Bank Security Alert","channel":"SMS","era":"2015–present","sophistication":"Medium","technique":"SMS claims suspicious activity on bank account, directs victim to call a number or click a link — both attacker-controlled","indicators":["bank name in message","suspicious activity claim","link or phone number provided"],"target_sector":"Banking Customers","success_rate":"High","source":"Preset DB"},
  {"id":"phi-024","type":"Business Email Compromise","subtype":"Real Estate / Conveyancing Fraud","channel":"Email","era":"2016–present","sophistication":"High","technique":"Attacker intercepts email chain between buyer and solicitor, substitutes bank account details at the moment of property completion","indicators":["email chain hijacking","last-minute bank detail change","solicitor impersonation"],"target_sector":"Property Buyers, Law Firms","success_rate":"Very High","source":"Preset DB"},
  {"id":"phi-025","type":"Credential Harvesting","subtype":"Fake VPN / Remote Access Login","channel":"Web","era":"2020–present","sophistication":"High","technique":"With rise of remote work, attackers created fake Cisco VPN, Citrix, and corporate SSO login pages to steal employee credentials at scale","indicators":["VPN brand cloned","corporate domain lookalike","targets remote workers"],"target_sector":"Remote Workers, IT Departments","success_rate":"High","source":"Preset DB"},
  {"id":"phi-026","type":"Spear Phishing","subtype":"Research / Academic Targeting","channel":"Email","era":"2017–present","sophistication":"High","technique":"Nation-state or competitor actors target academics and researchers with tailored lures to steal intellectual property or login credentials","indicators":["conference or journal impersonation","personalised research reference","credential harvesting disguised as paper submission"],"target_sector":"Academia, Research Institutions","success_rate":"High","source":"Preset DB"},
  {"id":"phi-027","type":"Email Phishing","subtype":"Crypto / NFT Investment Scam","channel":"Email + Social Media","era":"2020–present","sophistication":"Medium","technique":"Fake investment platform emails promise high returns in crypto, directing victims to deposit into attacker wallets or fake exchanges","indicators":["crypto returns promised","celebrity endorsement","urgency — limited slots"],"target_sector":"Retail Investors","success_rate":"Medium-High","source":"Preset DB"},
  {"id":"phi-028","type":"Credential Harvesting","subtype":"OAuth Consent Phishing","channel":"Web","era":"2020–present","sophistication":"Very High","technique":"Attacker sends legitimate-looking OAuth permission request for a malicious third-party app, gaining persistent access to Microsoft 365 or Google Workspace without needing the password","indicators":["OAuth consent screen","legitimate Microsoft/Google domain","unusual app permissions requested"],"target_sector":"Corporate Microsoft 365, Google Workspace","success_rate":"High","source":"Preset DB"},
  {"id":"phi-029","type":"Smishing","subtype":"Fake Fine / Penalty Notice","channel":"SMS","era":"2018–present","sophistication":"Low-Medium","technique":"SMS impersonating police, DVLA, or parking authority claiming outstanding fine with link to fake payment portal","indicators":["authority impersonation","fine or penalty language","payment link in SMS"],"target_sector":"General Public","success_rate":"Medium","source":"Preset DB"},
  {"id":"phi-030","type":"Spear Phishing","subtype":"AI-Generated Deepfake Lure","channel":"Email + Voice + Video","era":"2023–present","sophistication":"Very High","technique":"Uses AI-generated voice clones or video deepfakes of trusted contacts (executives, colleagues) to authenticate social engineering attacks at scale","indicators":["voice or video call from known person","unusual financial or credential request","short notice with high pressure"],"target_sector":"Corporate, Finance, Government","success_rate":"Emerging — High","source":"Preset DB"},
]

col.insert_many(PRESET)
print(f"Seeded {len(PRESET)} records into taxonomy_preset.")
